using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BookStore.Core.Entities
{
    public class Book
    {
        public int Id { get; set; } // Auto-generated by the database
        public string Title { get; set; }
        public string Author { get; set; }
        public decimal Price { get; set; }
        public int Stock { get; set; }
        public int NumberOfPages { get; set; }
        public DateTime PublishedDate { get; set; }
        public bool IsDiscounted { get; set; }
        public decimal DiscountedPrice { get; set; }
    }
}
